export const GET_TRENDING_MOVIES = "GET_TRENDING_MOVIES";
export const GET_TRENDING_MOVIES_SUCCESS = "GET_TRENDING_MOVIES_SUCCESS";
export const GET_TRENDING_MOVIES_ERROR = "GET_TRENDING_MOVIES_ERROR";

export const GET_TRENDING_TV = "GET_TRENDING_TV";
export const GET_TRENDING_TV_SUCCESS = "GET_TRENDING_TV_SUCCESS";
export const GET_TRENDING_TV_ERROR = "GET_TRENDING_TV_ERROR";
